# Generated by Django 5.1.3 on 2024-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_required',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('shave', 'Shave'), ('styling', 'Styling')], default='haircut', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stylist_preferred',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
