# Generated by Django 5.1.3 on 2024-11-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_stylist_preferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='additional_details',
        ),
    ]
